name: CI Tests

on:
  push:
    branches:
      - main

jobs:
  starting-tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Starting Tests
        run: pwd

  lint-ts:
    runs-on: ubuntu-latest
    needs: starting-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript Lint
        run: npx eslint

  type-check:
    runs-on: ubuntu-latest
    needs: starting-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Type Check
        run: npm run tsc --noEmit
      
  expo-doctor:
    runs-on: ubuntu-latest
    needs: starting-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Expo Doctor
        run: npx expo-doctor@latest
