name: CI Tests

on:
  push:
    branches:
      - main

jobs:
  starting-tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Starting Tests
        run: pwd

  lint-ts:
    runs-on: ubuntu-latest
    needs: starting-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript Lint
        run: npx eslint

  type-check:
    runs-on: ubuntu-latest
    needs: starting-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Type Check
        run: npx tsc
      


  code-tests:
    runs-on: ubuntu-latest
    needs: starting-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set execute permission for gradlew
        run: chmod +x ./backend/omniplanner/gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests
        run: | 
          cd backend/omniplanner 
          ./gradlew test
