name: CI Tests

on:
  push:
    branches:
      - main

jobs:
  init-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print working directory contents
        run: ls -al

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependancies
        run: npm install

  lint-ts:
    runs-on: ubuntu-latest
    needs: init-job
    steps:
      - name: Print working directory
        run: pwd
        
      - name: Print working directory contents
        run: ls -al

      - name: Run TypeScript Lint
        run: npx eslint

  type-check:
    runs-on: ubuntu-latest
    needs: init-job
    steps:
      - name: Run Type Check
        run: npm run tsc --noEmit
      
  expo-doctor:
    runs-on: ubuntu-latest
    needs: init-job
    steps:
      - name: Run Expo Doctor
        run: npx expo-doctor@latest

