name: Expo Doctor

on:
  workflow_run:
    workflows: ['Type Check']
    types: [completed]

jobs:
  run-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Run Expo Doctor
        run: npx expo-doctor@latest