name: Run All Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-workflows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: [expo-doctor.yml, lint-ts.yml, type-check.yml]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run ${{ matrix.workflow }}
        uses: ${{ matrix.workflow }}