name: Run All Workflows

on: [push, pull_request]

jobs:
  run-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Run the Expo Doctor workflow
      - name: Run Expo Doctor
        uses: ./.github/workflows/expo-doctor.yml

      # Run the TypeScript Lint workflow
      - name: Run TypeScript Lint
        uses: ./.github/workflows/lint-ts.yml

      # Run the Type Check workflow
      - name: Run Type Check
        uses: ./.github/workflows/type-check.yml
