name: Type Check

on:
  workflow_run:
    workflows: ['Linter']
    types: [completed]

jobs:
  run-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Run Type Check
        run: npm run tsc --noEmit