name: Type Check

on: [push, pull_request]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: setup
      uses: ./.github/actions/deps-install

    - name: Run TypeScript type check
      run: npm run tsc --noEmit
      working-directory: ./omni-planner
